### PR TITLE
First pass at S3 tests

### PR DESCRIPTION
**Pull request by hardillb**
## Description

Uses minio to provide S3 bucket.

Running locally

```
docker pull minio/minio
mkdir -p var/data/test
docker run --rm -v `pwd`/var/data:/data -p 9000:9000 minio/minio server /data
```

## Related Issue(s)

#40 

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [x] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by hardillb** [comment]
Basic test now run with S3 on GitHub

**Comment by Steve-Mcl** [comment]
@hardillb with new file system stuff and other progress, perhaps we should close this off for the time being?

**Comment by hardillb** [comment]
I'll fix the conflict and we can just merge it, but yes this code will get phased out soon.

**Comment by hardillb** [comment]
Hmm, bunch of none S3 test failures....

**Pull request closed without merging**
